spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
    driver-class-name: org.hibernate.dialect.PostgreSQLDialect
    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring:
 jpa:
 show-sql: true

spring:
  jpa:
  hibernate:
  ddl:
  auto: update

