spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: admin
    password: admin
   
    
  jpa:
    properties:
    hibernate:
    dialect : org.hibernate.dialect.PostgreSQLDialect
     

